// Pipeline — auto-generated
window.ITMEN_INITIAL = {
  "lists": {
    "stages": [
      "Взят в работу",
      "Встреча состоялась",
      "Интерес  Выявлен",
      "Подготовка Пилота",
      "Пилот",
      "Пилот Окончен",
      "Предложение выслано",
      "Согласование бюджета",
      "Финальный компред",
      "Условия согласованы",
      "Документы подписаны",
      "Отгружен",
      "Успешно реализовано",
      "На паузе"
    ],
    "dealTypes": [
      "Текущий пайплайн"
    ],
    "budgetStatus": [
      "Подтверждён",
      "В процессе согласования",
      "Планируется согласование",
      "Нет бюджета",
      "Неизвестно"
    ],
    "categories": [
      "Горячая",
      "Тёплая",
      "Наблюдение",
      "Отказ"
    ],
    "owners": [
      "Аркадий Мерлейн",
      "Арслан Ахметшин",
      "Александр Сироткин",
      "Алексей Кулагин"
    ],
    "industries": [
      "Банки",
      "Банки, Финансы",
      "Гос. предприятие",
      "Информационные технологии",
      "Медиа",
      "Медицина",
      "Металлы и добыча",
      "Металлы и добыча, Производство",
      "Металлы и добыча, Химия и нефтехимия",
      "Нефть и газ",
      "Нефть и газ, Транспорт",
      "Образование",
      "Производство",
      "Производство, Гос. предприятие",
      "Производство, Информационные технологии",
      "Производство, Химия и нефтехимия",
      "Ритейл",
      "Спорт",
      "Строительство",
      "Телекомм",
      "Телекомм, Медицина",
      "Транспорт",
      "Транспорт, Гос. предприятие",
      "Транспорт, Строительство",
      "Услуги",
      "Услуги, Транспорт",
      "Финансы",
      "Финансы, Информационные технологии",
      "Финансы, Транспорт",
      "Финансы, Услуги",
      "Химия и нефтехимия",
      "Химия и нефтехимия, Транспорт",
      "Хорека",
      "Электроэнергетика",
      "Не определена"
    ],
    "budgetPeriods": [
      "Q3 2026",
      "Q4 2026",
      "Q1 2027",
      "Q2 2027",
      "Q3 2027",
      "Q4 2027",
      "Не определён",
      "После 2027"
    ],
    "partners": [
      "ECO IT",
      "ICL компания",
      "IDEA PLATFORM (АйПи Консалтинг)",
      "IT Exept",
      "IT Expert",
      "Naumen",
      "RTM Group",
      "Sofline",
      "Sofltine",
      "Softline",
      "T1",
      "Андэк",
      "ГК Звезда",
      "Гигант",
      "ИТ Эксперт",
      "Инферит Техника",
      "К2",
      "КРОК",
      "ОНТЕГРА",
      "Софтлайн",
      "Т1",
      "Тринити Интеграция",
      "Юлэнд",
      "Нет партнёра",
      "Другой"
    ],
    "dml": [
      "CIO",
      "CISO",
      "IT-директор",
      "Руководитель ITSM",
      "Не определён"
    ]
  },
  "deals": [
    {
      "id": "D-001",
      "customer": "Татнефть",
      "industry": "Нефть и газ",
      "owner": "Не назначен",
      "stage": "3. Исследование",
      "dealType": "Текущий пайплайн",
      "amount": 0,
      "expectedBudget": 0,
      "partner": "Нет партнёра",
      "partnerDiscount": 0,
      "clientDiscount": 0,
      "manualProb": 0.6,
      "taskDue": "2026-09-15",
      "budgetPeriod": "Q1 след. года",
      "budgetStatus": "Запланирован",
      "budgetAmount": 0,
      "stack": "ITSM + инвентаризация TBD",
      "competitors": "TBD",
      "complexProject": "Возможно комплексный / TBD",
      "pains": "Бюджетирование август/сентябрь; нужна инвентаризация/учёт/качество CMDB",
      "capabilities": "Discovery, инвентаризация, отчёты, CMDB/API",
      "dml": "TBD",
      "scores": {
        "loyalty": 4,
        "budget": 4,
        "fit": 4,
        "timing": 4,
        "competitive": 3,
        "access": 3,
        "technical": 4,
        "commercial": 3
      },
      "scoreReasons": {},
      "scoreHistory": [],
      "scoresOverridden": {},
      "nextStepType": "discovery",
      "nextStepComment": "Получить подтверждение бюджетного цикла и список конкурентов",
      "riskType": "no_budget",
      "riskComment": "Нет внешнего подтверждения бюджета и конкурентов",
      "commitStatus": "verbal",
      "lastUpdate": "2026-06-19",
      "amoId": null,
      "techResearch": {
        "currentSolutions": "ITSM + инвентаризация TBD",
        "searchGoals": [],
        "searchComment": "",
        "pilotMode": "not_started",
        "pilotPartners": "",
        "reviewedProducts": [
          {
            "name": "TBD",
            "status": "evaluating",
            "rejectedReasons": [],
            "appealReasons": [],
            "openSource": "unknown",
            "origin": "unknown",
            "comment": ""
          }
        ],
        "integrationNotes": ""
      }
    },
    {
      "id": "D-002",
      "customer": "ГПН",
      "industry": "Нефть и газ",
      "owner": "Не назначен",
      "stage": "3. Исследование",
      "dealType": "Текущий пайплайн",
      "amount": 0,
      "expectedBudget": 0,
      "partner": "Нет партнёра",
      "partnerDiscount": 0,
      "clientDiscount": 0,
      "manualProb": 0.55,
      "taskDue": "2026-09-15",
      "budgetPeriod": "Q1 след. года",
      "budgetStatus": "Запланирован",
      "budgetAmount": 0,
      "stack": "ITSM/инфра стримы TBD",
      "competitors": "TBD",
      "complexProject": "Комплексный, несколько стримов",
      "pains": "Аудиты и пресейлы в других стримах; нужно понять контур и бюджет",
      "capabilities": "Discovery, агрегация данных, CMDB/API, отчёты",
      "dml": "TBD",
      "scores": {
        "loyalty": 3,
        "budget": 3,
        "fit": 4,
        "timing": 3,
        "competitive": 3,
        "access": 3,
        "technical": 4,
        "commercial": 2
      },
      "scoreReasons": {},
      "scoreHistory": [],
      "scoresOverridden": {},
      "nextStepType": "discovery",
      "nextStepComment": "Зафиксировать стрим, прайма, бюджет и нужный функционал",
      "riskType": "no_budget",
      "riskComment": "Неясен владелец бюджета и контур комплексного проекта",
      "commitStatus": "verbal",
      "lastUpdate": "2026-06-19",
      "amoId": null,
      "techResearch": {
        "currentSolutions": "ITSM/инфра стримы TBD",
        "searchGoals": [],
        "searchComment": "",
        "pilotMode": "not_started",
        "pilotPartners": "",
        "reviewedProducts": [
          {
            "name": "TBD",
            "status": "evaluating",
            "rejectedReasons": [],
            "appealReasons": [],
            "openSource": "unknown",
            "origin": "unknown",
            "comment": ""
          }
        ],
        "integrationNotes": ""
      }
    },
    {
      "id": "D-003",
      "customer": "Клиент X",
      "industry": "TBD",
      "owner": "Не назначен",
      "stage": "2. Квалификация",
      "dealType": "Текущий пайплайн",
      "amount": 0,
      "expectedBudget": 0,
      "partner": "Нет партнёра",
      "partnerDiscount": 0,
      "clientDiscount": 0,
      "manualProb": 0.3,
      "taskDue": "2026-08-31",
      "budgetPeriod": "Q4",
      "budgetStatus": "Неизвестно",
      "budgetAmount": 0,
      "stack": "TBD",
      "competitors": "TBD",
      "complexProject": "TBD",
      "pains": "Заполнить после интервью",
      "capabilities": "TBD",
      "dml": "TBD",
      "scores": {
        "loyalty": 0,
        "budget": 0,
        "fit": 0,
        "timing": 0,
        "competitive": 0,
        "access": 0,
        "technical": 0,
        "commercial": 0
      },
      "scoreReasons": {},
      "scoreHistory": [],
      "scoresOverridden": {},
      "nextStepType": "discovery",
      "nextStepComment": "Заполнить паспорт и назначить следующий контакт",
      "riskType": "none",
      "riskComment": "Нет фактуры",
      "commitStatus": "none",
      "lastUpdate": "2026-06-19",
      "amoId": null,
      "techResearch": {
        "currentSolutions": "TBD",
        "searchGoals": [],
        "searchComment": "",
        "pilotMode": "not_started",
        "pilotPartners": "",
        "reviewedProducts": [
          {
            "name": "TBD",
            "status": "evaluating",
            "rejectedReasons": [],
            "appealReasons": [],
            "openSource": "unknown",
            "origin": "unknown",
            "comment": ""
          }
        ],
        "integrationNotes": ""
      }
    }
  ],
  "scoring": [
    {
      "name": "Лояльность контакта",
      "col": "T",
      "weight": 0.15,
      "s5": "Чемпион + доступ к ЛПР",
      "s3": "Регулярный контакт, без ЛПР",
      "s1": "Контакт низкого уровня",
      "s0": "Нет контакта",
      "owner": "Продажи"
    },
    {
      "name": "Определённость бюджета",
      "col": "U",
      "weight": 0.2,
      "s5": "Бюджет подтверждён, сумма известна",
      "s3": "Бюджет запланирован, цикл известен",
      "s1": "Бюджет предполагается",
      "s0": "Нет бюджета / неизвестно",
      "owner": "Продажи + Финансы"
    },
    {
      "name": "Соответствие проблеме",
      "col": "V",
      "weight": 0.2,
      "s5": "Ключевая боль решается ITMen",
      "s3": "Сильное соответствие с пробелами",
      "s1": "Косвенное соответствие",
      "s0": "Нет явной боли",
      "owner": "Продукт + Пресейл"
    },
    {
      "name": "Срочность сроков",
      "col": "W",
      "weight": 0.15,
      "s5": "Решение в Q3/Q4 с триггером",
      "s3": "Решение в Q1 след. года",
      "s1": "Длинный цикл, слабый триггер",
      "s0": "Нет сроков",
      "owner": "Продажи"
    },
    {
      "name": "Конкурентная позиция",
      "col": "X",
      "weight": 0.1,
      "s5": "Мы предпочтительны / дифференцированы",
      "s3": "В шорт-листе",
      "s1": "Коммодити-сравнение",
      "s0": "Выбран конкурент",
      "owner": "Продажи"
    },
    {
      "name": "Доступ / влияние",
      "col": "Y",
      "weight": 0.1,
      "s5": "Карта влияния известна, доступ к CEO",
      "s3": "Есть некоторое влияние",
      "s1": "Карта неизвестна",
      "s0": "Нет доступа",
      "owner": "Продажи"
    },
    {
      "name": "Техническое соответствие",
      "col": "Z",
      "weight": 0.05,
      "s5": "Критичной разработки не нужно",
      "s3": "Небольшой scope",
      "s1": "Средняя разработка",
      "s0": "Серьёзный пробел",
      "owner": "Пресейл"
    },
    {
      "name": "Коммерческая готовность",
      "col": "AA",
      "weight": 0.05,
      "s5": "КП/условия договора готовы",
      "s3": "Черновик КП",
      "s1": "Нет коммерческих условий",
      "s0": "Не коммерциализировано",
      "owner": "Продажи"
    }
  ],
  "pipelineFocus": {
    "title": "Текущий пайплайн — активен",
    "goal": "Коммиты клиентов, даты бюджета, top-10 артефактов",
    "risk": "Пайплайн на словах или уходит на след. год",
    "nextStep": "Неделя 2 — скоринг и классификация сделок"
  },
  "nextId": 4
};
